data: ../dataset_yolo11_seg/dataset.yaml
model_yaml: configs/yolo11s-seg-p2.yaml
pretrained: models/best.pt
epochs: 100
imgsz: 960
batch: 4
device: "0"
workers: 0
amp: true
mask_ratio: 2
overlap_mask: true
close_mosaic: 10
cos_lr: true
patience: 30
save_period: 10
project: runs/segment
name: p2_yolo11s_seg_960_continue
exist_ok: false
plots: true
deterministic: true
seed: 0
